// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movies.Api.Data;

#nullable disable

namespace Movies.Api.Data.Migrations
{
    [DbContext(typeof(MoviesContext))]
    [Migration("20221125121618_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("Movies.Api.Data.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DirectorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("MovieId");

                    b.HasIndex("DirectorId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            DirectorId = 6,
                            ReleaseDate = new DateTime(2015, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Star Wars: The Force Awakens"
                        },
                        new
                        {
                            MovieId = 2,
                            DirectorId = 6,
                            ReleaseDate = new DateTime(2009, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Star Trek"
                        },
                        new
                        {
                            MovieId = 3,
                            DirectorId = 7,
                            ReleaseDate = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Star Trek Beyond"
                        },
                        new
                        {
                            MovieId = 4,
                            DirectorId = 7,
                            ReleaseDate = new DateTime(2009, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fast & Furious"
                        },
                        new
                        {
                            MovieId = 5,
                            DirectorId = 7,
                            ReleaseDate = new DateTime(2011, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fast Five"
                        },
                        new
                        {
                            MovieId = 6,
                            DirectorId = 7,
                            ReleaseDate = new DateTime(2013, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fast & Furious 6"
                        },
                        new
                        {
                            MovieId = 7,
                            DirectorId = 7,
                            ReleaseDate = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Hollywood Adventures"
                        },
                        new
                        {
                            MovieId = 8,
                            DirectorId = 6,
                            ReleaseDate = new DateTime(2013, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Star Trek Into Darkness"
                        },
                        new
                        {
                            MovieId = 9,
                            DirectorId = 6,
                            ReleaseDate = new DateTime(2006, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mission: Impossible III"
                        });
                });

            modelBuilder.Entity("Movies.Api.Data.MovieActor", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MovieId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonId", "MovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieActors");

                    b.HasData(
                        new
                        {
                            PersonId = 2,
                            MovieId = 1
                        },
                        new
                        {
                            PersonId = 2,
                            MovieId = 2
                        },
                        new
                        {
                            PersonId = 3,
                            MovieId = 2
                        });
                });

            modelBuilder.Entity("Movies.Api.Data.Nationality", b =>
                {
                    b.Property<int>("NationalityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("NationalityId");

                    b.ToTable("Nationalities");

                    b.HasData(
                        new
                        {
                            NationalityId = 1,
                            Title = "British"
                        },
                        new
                        {
                            NationalityId = 2,
                            Title = "French"
                        },
                        new
                        {
                            NationalityId = 3,
                            Title = "American"
                        });
                });

            modelBuilder.Entity("Movies.Api.Data.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NationalityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonId");

                    b.HasIndex("NationalityId");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            Birthday = new DateTime(2022, 11, 25, 12, 16, 18, 248, DateTimeKind.Local).AddTicks(203),
                            FirstName = "Larry",
                            LastName = "Losser",
                            NationalityId = 1
                        },
                        new
                        {
                            PersonId = 2,
                            Birthday = new DateTime(1970, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Simon",
                            LastName = "Pegg",
                            NationalityId = 1
                        },
                        new
                        {
                            PersonId = 3,
                            Birthday = new DateTime(1976, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Benedict",
                            LastName = "Cumberbatch",
                            NationalityId = 1
                        },
                        new
                        {
                            PersonId = 4,
                            Birthday = new DateTime(1948, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jean",
                            LastName = "Reno",
                            NationalityId = 2
                        },
                        new
                        {
                            PersonId = 5,
                            Birthday = new DateTime(1980, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Chris",
                            LastName = "Pine",
                            NationalityId = 3
                        },
                        new
                        {
                            PersonId = 6,
                            Birthday = new DateTime(1966, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "JJ",
                            LastName = "Abrams",
                            NationalityId = 3
                        },
                        new
                        {
                            PersonId = 7,
                            Birthday = new DateTime(1971, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Justin",
                            LastName = "Lin",
                            NationalityId = 3
                        });
                });

            modelBuilder.Entity("Movies.Api.Data.Movie", b =>
                {
                    b.HasOne("Movies.Api.Data.Person", "Director")
                        .WithMany()
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Director");
                });

            modelBuilder.Entity("Movies.Api.Data.MovieActor", b =>
                {
                    b.HasOne("Movies.Api.Data.Movie", "Movie")
                        .WithMany("Actors")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Movies.Api.Data.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Movies.Api.Data.Person", b =>
                {
                    b.HasOne("Movies.Api.Data.Nationality", "Nationality")
                        .WithMany()
                        .HasForeignKey("NationalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nationality");
                });

            modelBuilder.Entity("Movies.Api.Data.Movie", b =>
                {
                    b.Navigation("Actors");
                });
#pragma warning restore 612, 618
        }
    }
}
