// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThAmCo.Catering.DatabaseContexts;

#nullable disable

namespace ThAmCo.Catering.Migrations
{
    [DbContext(typeof(CateringDbContext))]
    [Migration("20231026130137_inital")]
    partial class inital
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.23");

            modelBuilder.Entity("ThAmCo.Catering.Data.FoodBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MenuId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FoodBookings");
                });

            modelBuilder.Entity("ThAmCo.Catering.Data.FoodItem", b =>
                {
                    b.Property<int>("FoodItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("REAL");

                    b.HasKey("FoodItemId");

                    b.ToTable("FoodItems");

                    b.HasData(
                        new
                        {
                            FoodItemId = 1,
                            Description = "Prawn Cocktail",
                            UnitPrice = 6.9900000000000002
                        },
                        new
                        {
                            FoodItemId = 2,
                            Description = "Scotch Egg",
                            UnitPrice = 8.4900000000000002
                        },
                        new
                        {
                            FoodItemId = 3,
                            Description = "Soup of the Day",
                            UnitPrice = 4.9900000000000002
                        },
                        new
                        {
                            FoodItemId = 4,
                            Description = "Deviled Whitebait",
                            UnitPrice = 7.9900000000000002
                        },
                        new
                        {
                            FoodItemId = 5,
                            Description = "Stilton and Broccoli Bites",
                            UnitPrice = 6.4900000000000002
                        },
                        new
                        {
                            FoodItemId = 6,
                            Description = "Full-English Breakfast",
                            UnitPrice = 9.9900000000000002
                        },
                        new
                        {
                            FoodItemId = 7,
                            Description = "Shepherd's Pie",
                            UnitPrice = 12.99
                        },
                        new
                        {
                            FoodItemId = 8,
                            Description = "Bangers and Mash",
                            UnitPrice = 11.99
                        },
                        new
                        {
                            FoodItemId = 9,
                            Description = "Ploughman's Lunch",
                            UnitPrice = 7.9900000000000002
                        },
                        new
                        {
                            FoodItemId = 10,
                            Description = "Cornish Pasty",
                            UnitPrice = 6.9900000000000002
                        },
                        new
                        {
                            FoodItemId = 11,
                            Description = "Beef Wellington",
                            UnitPrice = 18.989999999999998
                        },
                        new
                        {
                            FoodItemId = 12,
                            Description = "Black Pudding",
                            UnitPrice = 8.9900000000000002
                        },
                        new
                        {
                            FoodItemId = 13,
                            Description = "Bubble and Squeak",
                            UnitPrice = 6.4900000000000002
                        },
                        new
                        {
                            FoodItemId = 14,
                            Description = "Stilton Cheese",
                            UnitPrice = 14.99
                        },
                        new
                        {
                            FoodItemId = 15,
                            Description = "Fish and Chips",
                            UnitPrice = 8.9900000000000002
                        },
                        new
                        {
                            FoodItemId = 16,
                            Description = "Sticky Toffee Pudding",
                            UnitPrice = 7.4900000000000002
                        },
                        new
                        {
                            FoodItemId = 17,
                            Description = "Trifle",
                            UnitPrice = 6.9900000000000002
                        },
                        new
                        {
                            FoodItemId = 18,
                            Description = "Apple Crumble",
                            UnitPrice = 5.9900000000000002
                        },
                        new
                        {
                            FoodItemId = 19,
                            Description = "Eton Mess",
                            UnitPrice = 8.4900000000000002
                        },
                        new
                        {
                            FoodItemId = 20,
                            Description = "Victoria Sponge Cake",
                            UnitPrice = 9.9900000000000002
                        });
                });

            modelBuilder.Entity("ThAmCo.Catering.Data.Menu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MenuName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("MenuId");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("ThAmCo.Catering.Data.MenuFoodItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FoodItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MenuId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MenusFoodItems");
                });
#pragma warning restore 612, 618
        }
    }
}
